#!/usr/bin/env bash

set -x # Show commands
set -eu # Errors/undefined vars are fatal
set -o pipefail # Check all commands in a pipeline

date

# Add the special clang flags.
$MOZSEARCH_PATH/scripts/indexer-setup.py > $INDEX_ROOT/config
. $INDEX_ROOT/config

mkdir -p $OBJDIR

cd $FILES_ROOT
./configure --without-readline
make
cd -

date
